### ISSUE TITLE
[FR] module info from command line

### ISSUE THREAD

**Issue by ildar** [sezero/mikmod#1]
mikmod can run and process from command line, that's great.
I'd want to extract module info from command line, e.g. name. Thanks.

**Comment by alexmyczko** [comment]
why not use https://github.com/file/file ?

**Comment by ildar** [comment]
Thanks for your advice.
IIRC `file` doesn't cover all formats that mikmod supports. So it's a
partial solution.

**Comment by AliceLR** [comment]
FWIW I think xmp can do something similar to what was requested here with the `--load-only` command line option.
