### ISSUE TITLE
Mikmod does not play zip archives

### ISSUE THREAD

**Issue by vondrt4** [sezero/mikmod#2]
Hi!
After many years, I wanted to play the collection from ftp.hornet.org, which is all zipped. It used to work with mikmod, but does not anymore. Can't say when it got broken. I just remember using Mikmod on Debian 3.0. Now on 9.0 zip files are not recognized.

**Comment by sezero** [comment]
NOTE: Bug reports should be at https://sourceforge.net/projects/mikmod/ and not here.

As for the issue: I am on fedora 27 which ships mikmod-3.2.8/libmikmod-3.3.11.1,
I downloaded ftp://ftp.hornet.org/pub/demos/music/songs/1998/a/a-cloud.zip
and it plays the contained song. So, I cannot reproduce.  Maybe it has something
to do with debian's own packaging. (You do have zip installed, don't you?)

**Comment by vondrt4** [comment]
You could disable the Issues functionality of Github. But then you should put the location of the bug tracker on the project homepage. Frankly, I would never have looked for a bug tracker on Sourceforge.

Debian 9 has mikmod 3.2.7 and libmikmod 3.3.10. I even tried compiling it from source, so there's probably no problem with Debian packaging.
I have both zip and unzip installed.
I have a .mikmodrc file that contains the archiver definitions.
Unzip seems to accept the right command-line switches:
$ unzip -vqq florence.zip 
255412  Defl:N   164510  36% 1993-07-02 08:55 0f1d0115  FLORENCE.MOD
What else can be wrong?

**Comment by vondrt4** [comment]
Found it. It was the nameoffset for unzip file listing. The default - 58 - left one space before the actual file name. Putting 59 there fixed it. Unzip is version 6.0, by the way.

**Comment by sezero** [comment]
> Found it. It was the nameoffset for unzip file listing. The default - 58
> - left one space before the actual file name. Putting 59 there fixed it.

My .mikmodrc has the same 58 name offset as yours, but
ftp://ftp.hornet.org/pub/demos/music/songs/1991/florence.zip
plays fine for me

> Unzip is version 6.0, by the way.

Mine is too
```
$ rpm -q unzip
unzip-6.0-37.fc27.x86_64
$ unzip -vqq florence.zip
  255412  Defl:N   164510  36% 07-02-1993 08:55 0f1d0115  FLORENCE.MOD
```

(I can't exactly compare your output to mine, because yours is whitespace-
mangled by github's interface.)

**Comment by sezero** [comment]
PS:  This seems more like an issue with debian's unzip.
