### ISSUE TITLE
I created a Web Audio wrapper/example in a forked repo

### ISSUE THREAD

**Issue by carlosrafaelgn** [sezero/mikmod#52]
Hi everyone!

I have just created a web audio wrapper for libmikmod.

Not a single file has been changed in the entire library!

All I did was to create a new folder inside libmikmod, called webaudio, and placed everything needed in there, including two sample HTML pages and the distributed files.

https://github.com/carlosrafaelgn/mikmod/tree/master/libmikmod/webaudio

I uploaded the example so you could see it working (tested OK on Chrome 91, Edge 91, and Firefox 90):
- https://fplay.com.br/examples/exampleSimple.html
- https://fplay.com.br/examples/exampleOptions.html

My question is:

After creating these missing files, could I create a pull request? Or should I just leave these files in my repo?... Or should I move these files elsewhere, perhaps creating an entire new repo for them?

**Comment by sezero** [comment]
I'd say that you create a pull request, so everyone would be aware
of it if nothing else.

**Comment by carlosrafaelgn** [comment]
Thanks! I just created a pull request 😊
