### ISSUE TITLE
[Feature request] Building without texinfo dependency

### ISSUE THREAD

**Issue by vanfanel** [sezero/mikmod#53]
Hi @sezero 

I was surprised you are in charge of this classic mikmod! Thanks!

I would like to ask you if it would be possible to add an option to build without texinfo dependency, as that pulls 11MB of dependencies.

This is what currently happens if I try, since makeinfo (part of texinfo) is not found:
```

/bin/sh: 1: MAKEINFO_EXECUTABLE-NOTFOUND: not found
make[2]: *** [docs/CMakeFiles/info.dir/build.make:62: docs/mikmod.info] Error 127
make[1]: *** [CMakeFiles/Makefile2:320: docs/CMakeFiles/info.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I believe `makeinfo` is needed to generate html docs, which could be optional in such a basic library.

**Comment by sezero** [comment]
You can do `--disable-doc` with autotools, or `cmake -DENABLE_DOC=0` with cmake.
Does it work for you?

**Comment by vanfanel** [comment]
@sezero Yes! It works perfectly! Thanks a lot! :)
