### ISSUE TITLE
Missing support for Mod's Grave .WOW 8CHN .MOD variant.

### ISSUE THREAD

**Issue by AliceLR** [sezero/mikmod#7]
As far as I can tell from looking at the .MOD loader there's no support for [this odd .MOD variant](https://modland.com/pub/documents/format_documentation/Mod's%20Grave,%20Grave%20Composer%20(.wow).txt). It's essentially an `8CHN` .MOD with an `M.K.` signature and the only way to detect this is to calculate the expected size of an `8CHN` .MOD and see if the input file has the same length. MikMod interprets them as standard 4-channel `M.K.` .MODs and the playback is about what you'd expect from that.

I don't know if any of these actually exist in the wild or that these are worth supporting. This .WOW was created with the Mod's Grave `6692WOW.EXE` converter from a small .669 I had available. Despite what the doc claims I haven't found any evidence that "Grave Composer" actually exists; Mod's Grave is a DOS .MOD player and .WOW seems to exist solely as a format so it can support .669s.

[crystals.669.zip](https://github.com/sezero/mikmod/files/5370808/crystals.669.zip)
[CRYSTALS.WOW.zip](https://github.com/sezero/mikmod/files/5370834/CRYSTALS.WOW.zip) (Warning: sounds pretty bad when played by MikMod)
[grave105.arj.zip](https://github.com/sezero/mikmod/files/5370813/grave105.arj.zip) (Documentation is in German. Sorry for the double archiving, Github doesn't like .arj).

Unrelatedly, that .669 feels like it plays back a little bit slower than with libxmp and libmodplug, but I don't know if that's a bug.

**Comment by sezero** [comment]
Do you have a well-tested patch?

**Comment by AliceLR** [comment]
This one ended up requiring a bit of research and I'm glad I checked into it. libxmp and libmodplug both have buggy .WOW detection.

Since due to the nature of this weird format false positives are a big potential problem, I [wrote a utility to simulate loading various .MODs](https://github.com/AliceLR/megazeuxtests/blob/master/src/wowutil.cpp) to iron out issues in .WOW detection and to gather information about how many .MODs in the wild may be likely to cause false positives in .WOW detection. I also converted every .669 I have to .WOW using the Mod's Grave converter to test this util with and to examine them with a hex editor.

Here are the output files from that utility when used on a) all successfully converted .WOW files, b) Mods Anthology, and c) Mod Archive (thanks to a friend who already had Mod Archive's .MOD collection mirrored on a server to test with):

[output.zip](https://github.com/sezero/mikmod/files/5390376/output.zip) (note: large .txt files, maybe not particularly interesting to anyone but me.)

Generally what I found was:
* Most .MOD files have a fairly predictable filesize and in most of the .MOD files that aren't, their filesize issues seem to be caused by truncation or junk sample data lingering. From all of the .MOD files in the Mod Archive, only a single file causes any issues. Here's the file in question; try loading it with mikmod and then try loading it with xmp:
[ponylips.mod.zip](https://github.com/sezero/mikmod/files/5390362/ponylips.mod.zip)

* Mod's Grave .WOW files are nearly as predictable as the document I linked in the first comment suggests, with the exceptions that 1) for a very small number of .WOW files it will add an extra byte for some reason and 2) certain .669 files just fail to convert and the resulting .WOW is corrupted. The former is easy to deal with and the latter doesn't matter. Sample .669 that results in a .WOW with the rare extra byte:
[acid funk.669.zip](https://github.com/sezero/mikmod/files/5390356/acid.funk.669.zip)
[ACIDFU~1.WOW.zip](https://github.com/sezero/mikmod/files/5390357/ACIDFU.1.WOW.zip)

* .WOW files always have `0x00` for the restart byte, which is useful. The .669 looping feature is converted to a pattern jump command and does not affect this byte. Anything without `0x00` here isn't a .WOW. Sample .669 with a loop position set that gets converted to a pattern jump:
[1rex.669.zip](https://github.com/sezero/mikmod/files/5390352/1rex.669.zip)
[1REX.WOW.zip](https://github.com/sezero/mikmod/files/5390353/1REX.WOW.zip)

* Since .WOW files are based on .669s, they always use default sample finetune and volume info. Anything without `0x0040` for these values isn't a .WOW.

Since both of the two checks I listed prevent ponylips.mod from being mistaken for a .WOW and no other files had this issue I went ahead and made a [patch implementing support for this format](https://github.com/sezero/mikmod/compare/master...AliceLR:add-mods-grave-support). It still needs more testing before I'm comfortable opening a PR but I think at the very least it shouldn't break anything that worked before.

More on why ponylips.mod causes problems: the file is 9216 bytes larger than expected, which just happens to correspond to the exact amount of extra pattern data that is required for the .WOW check to succeed `(9 * 4 * 4 * 64)`. libxmp and libmodplug don't implement any other checks to make sure the file isn't a .WOW, so they load it incorrectly. libopenmpt successfully loads it because it removes length=1 samples, altering the calculated length (though this causes problems with detecting some .WOWs). Looking at the end of the file in a hex editor, it looks like it was intentionally padded with text, but it's not obvious why.
