### ISSUE TITLE
XM files containing order skip byte 0xFE do not play correctly.

### ISSUE THREAD

**Issue by AliceLR** [sezero/mikmod#8]
.XM files containing the .S3M/.IT order skip byte 0xFE will play an empty pattern instead of skipping that order.

Here's an example file I created in Modplug 1.16 a while back (it's not a particularly good track, sorry... ☹️).
[vs_battle.xm.zip](https://github.com/sezero/mikmod/files/5373676/vs_battle.xm.zip)

This might be a Modplug-exclusive extension to the .XM format, but other .XMs in the wild might have these. libxmp handles these as expected but I can't tell if that's intentional.

Also, the S3MIT_CreateOrders behavior of stripping out 0xFE bytes from the order list causes sngpos / Player_GetOrder / Player_SetPosition to use different order numbers than the original track. This will break anything outside of MikMod relying on the original order positions (many MegaZeux games rely on hardcoded order numbers but I don't know how many of those also use 0xFE...). edit: that's unless there's a documented way to convert between the two sets of order numbers I missed.

**Comment by sezero** [comment]
Do you have a well-tested patch?

**Comment by AliceLR** [comment]
No. I'm not sure how you'd like this issue fixed (if at all). 0xFE appears to be within the valid pattern range of (normal) .XM files (no test case yet) so this one might need to be handled carefully.

**Comment by sagamusix** [comment]
> This might be a Modplug-exclusive extension to the .XM format

It is. OpenMPT won't allow you to use +++ and --- patterns any more in XM files. When importing old ModPlug files, it checks if patterns 254 and 255 actually exist and if they don't, it assumes ModPlug semantics, otherwise "correct" FT2 semantics.

**Comment by sezero** [comment]
How large would be the volume of XM files out there with this extension?
I.e. do we actually need to fix this? (how does libxmp behave with this case?)

**Comment by AliceLR** [comment]
As far as I can tell libxmp has no special handling for this—it leaves these bytes in the order list and unconditionally skips orders >= the pattern count during playback.

https://github.com/cmatsuoka/libxmp/blob/master/src/scan.c#L150

**Comment by AliceLR** [comment]
I wrote [a program to check .XMs for this ModPlug extension](https://github.com/AliceLR/megazeuxtests/blob/master/src/xmutil.cpp) and found a total of three of these in the ModLand 2014 dump (Mod Archive data pending). Interestingly there are a lot more XMs with orders higher than the pattern count so I wonder if I made a mistake...

[XMs_ModLand.txt](https://github.com/sezero/mikmod/files/5398267/XMs_ModLand.txt) (4.2 MB)
[XMs_with_skip.zip](https://github.com/sezero/mikmod/files/5398268/XMs_with_skip.zip)

**Comment by sezero** [comment]
So, only a handful of files in the wild, but libxmp plays them correctly (right?)

Unless you have a patch, this will be a wont-fix.

**Comment by AliceLR** [comment]
Right, libxmp does play these correctly. There are 6 more of these in the Mod Archive collection, for a total of 10. I agree that supporting an obscure ModPlug-specific hack just for these is probably a waste of time.

Looking into the "invalid" patterns my utility detected, it looks like XM does the same thing as STM does (#9), and in the case of XM, libxmp and MikMod already handle this behavior correctly. This also means MikMod likely does the correct thing in converting these 0xFE patterns into blanks. So TL;DR, no bugs here (and sorry for the useless report!).
